### ISSUE TITLE
Missing Json body in POST API request when you re-open Object Repo

### ISSUE THREAD

**Issue by trongbui** [katalon-studio/katalon-studio#89] opened 2019-02-08 16:30 UTC
https://katalon.zendesk.com/agent/tickets/218

Observation of POST API Request 
1) Initial json body visible and works until object repo is open(InitialCapture.PNG) 
2) when re-opened found json empty, couldn't modify the body when re-opened for existing json object repo(re-open.PNG) 
3) without the json body visibility, was able to make API request(withoutJson.PNG)

This is weird behaviour , didn't expect it

**Comment by kms-loantran** [comment] 2019-02-12 09:31
I cannot reproduce this issue. Json data kept and displays correctly as always on both MAC and Win

**Comment by manumahendran** [comment] 2019-03-01 05:41
Hey, Steps to reproduce
Create a REST/SOAP test object
Populate the request body
Save
run a test
Close Katalon and reopen
The request body field is empty

**Comment by trongbui** [comment] 2019-03-01 06:49
Oliver, this is very frequently happening to us. 
Yes once the API is created then I can test. But everytime I restart katalon or re-open the project, I'm having to re-enter the request body. Can you fix this asap? It is really annoying as we are stepping to webservice testing phase. How can I expedite this?

**Comment by duyluonganh** [comment] 2019-03-29 07:32
Supported in v6.1.2

**Comment by nikhitakale** [comment] 2019-08-06 08:57
This issue is still re-producing in Katalon Version 6.1.2
OS used: Ubuntu 14

**Comment by frinux** [comment] 2019-09-11 09:17
Reproducing it on Katalon Version: 6.3.3 Build: 11
OS: Ubuntu 19.04

**Scenario 1**: in HTTP Body, enter the JSON in "text" tab
- HTTP Body is NEVER sent
- close the request and re-open it: the textarea is empty

**Scenario 2**: in HTTP Body, enter a JSON file in "file" tab
- HTTP Body is sent: OK
- BUT the "pretty" view is empty, only the preview is OK. Makes it hard to read JSON responses.

**Comment by Padoplin** [comment] 2020-02-19 09:07
@huynguyen2908 please verify this issue.

**Comment by POSEIDONCHIK** [comment] 2020-06-22 08:15
> @huynguyen2908 please verify this issue.

I have trouble with missimg request body in Katalon_Studio_Linux_64-7.5.5 on Ubuntu 18.04
In HAR bodysize always == 0.

**Comment by Padoplin** [comment] 2020-12-09 09:30
Hello everyone

This bug is fixed in verison 7.8+. Please upgrade!

Jass

**Closed by Padoplin** 2020-12-09 09:30 UTC
Labels: affects-version:7.5.5, bug, p:high, s:critical
